# Generated by Django 3.2 on 2023-11-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='pub_date',
        ),
    ]
