# Generated by Django 3.2 on 2023-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='categories',
        ),
        migrations.AddField(
            model_name='titles',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='reviews.Categories'),
        ),
    ]
