# Generated by Django 3.2 on 2023-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_genres_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='author',
        ),
    ]
