# Generated by Django 3.2 on 2023-11-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_remove_genres_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='user.customuser'),
            preserve_default=False,
        ),
    ]
