# Generated by Django 3.2 on 2023-11-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_titles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='author',
        ),
    ]
